apiVersion: v1
appVersion: "1.0"
description: A Helm chart for bank vault operator
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
name: preview
version: 0.1.0
